[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "CTNOriginals"
name = "FrontDesk"
description = "Moves the boarding desk from across the airport to the entrance instead to save you the long commute."
websiteUrl = "https://github.com/CTNOriginals/PEAK-FrontDesk"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_PEAK = "5.4.2403"

[build]
icon = "../icon.png"
readme = "../README.md"
outdir = "../artifacts/thunderstore/"

[[build.copy]]
source = "../artifacts/bin/FrontDesk/release/com.CTNOriginals.peak.FrontDesk.dll"
target = "plugins/"

[[build.copy]]
source = "../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../LICENSE"
target = "/"

[publish]
# See communities at:
# https://thunderstore.io/api/experimental/community/
communities = [ "peak" ]

[publish.categories]
# See categories at:
# https://thunderstore.io/api/experimental/community/peak/category/
peak = [ "mods", "misc" ]
